# Python runtime as a parent image
FROM python:3.9-slim

# Install packages
RUN pip install flask

#set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Expose port 80
EXPOSE 80

# Run .py when the container launches
CMD ["python", "./hello-there-back.py"]

