version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile_back
    ports:
      - "5001:5001"
    networks:
      - app-network
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "80:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

