version: '3'
services:
  frontend:
    image: gilibee/hello-there-front
    ports:
      - "80:5000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: gilibee/hello-there-back
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

